// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrs99LgWQzv5Jy5Gvh7kPjab49IUUu7vw',
    appId: '1:501226329148:web:433477b984647c2feadf39',
    messagingSenderId: '501226329148',
    projectId: 'chat-app-b39b3',
    authDomain: 'chat-app-b39b3.firebaseapp.com',
    storageBucket: 'chat-app-b39b3.appspot.com',
    measurementId: 'G-WCP3L1E89D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3RIJsdhyZB3xKocMoUkLjg_BbLVabGFM',
    appId: '1:501226329148:android:f5b76896a71acf65eadf39',
    messagingSenderId: '501226329148',
    projectId: 'chat-app-b39b3',
    storageBucket: 'chat-app-b39b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnDJZsyR1-fHhyk9LxfBdOtRyvAXHIs4I',
    appId: '1:501226329148:ios:616def1f98e18b3deadf39',
    messagingSenderId: '501226329148',
    projectId: 'chat-app-b39b3',
    storageBucket: 'chat-app-b39b3.appspot.com',
    iosClientId: '501226329148-itu2i3rsouqvulpt13telnatc51upvl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnDJZsyR1-fHhyk9LxfBdOtRyvAXHIs4I',
    appId: '1:501226329148:ios:f3785e41629f0e79eadf39',
    messagingSenderId: '501226329148',
    projectId: 'chat-app-b39b3',
    storageBucket: 'chat-app-b39b3.appspot.com',
    iosClientId: '501226329148-oh1qa4403kcq7sr1e5pmohbpqssh6hjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
